### ISSUE TITLE
Erreur Better-Sqlite3 Sur Termux 0.118.0

### ISSUE THREAD

**Issue by localht** [whoisbaby/CrowBot-Remade#2]
avec le fichier zip que tu as mis sur le README.md l'erreur suivante s'affiche

.../0/77P $ node index
/storage/emulated/0/77P/node_modules/bindings/bindings.js:123
        throw e;
        ^

Error: dlopen failed: "/storage/emulated/0/77P/node_modules/better-sqlite3/build/Release/better_sqlite3.node" has bad ELF magic: 4d5a9000
    at Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/storage/emulated/0/77P/node_modules/bindings/bindings.js:112:48)
    at new Database (/storage/emulated/0/77P/node_modules/better-sqlite3/lib/database.js:48:64)
    at Object.<anonymous> (/storage/emulated/0/77P/node_modules/quick.db/src/index.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.3.0

avec l'installation du node_modules depuis replit l'erreur suivante s'affiche

/storage/emulated/0/77PCrowbot/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen failed: "/storage/emulated/0/77PCrowbot/node_modules/better-sqlite3/build/Release/better_sqlite3.node" is 64-bit instead of 32-bit
    at Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/storage/emulated/0/77PCrowbot/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/storage/emulated/0/77PCrowbot/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.3.0

sur installation locale 

/data/data/com.termux/files/home/protect/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/compiled/18.3.0/android/arm/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /data/data/com.termux/files/home/protect/node_modules/better-sqlite3/lib/binding/node-v108-android-arm/better_sqlite3.node
    at bindings (/data/data/com.termux/files/home/protect/node_modules/bindings/bindings.js:126:9)
    at new Database (/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/lib/database.js:48:64)
    at Object.<anonymous> (/data/data/com.termux/files/home/protect/node_modules/quick.db/src/index.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/protect/node_modules/quick.db/index.js:7:18) {
  tries: [
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/compiled/18.3.0/android/arm/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/data/data/com.termux/files/home/protect/node_modules/better-sqlite3/lib/binding/node-v108-android-arm/better_sqlite3.node'
  ]
}

Node.js v18.3.0

**Comment by invalidprocess** [comment]
npm rebuild
